# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0003_auto_20161219_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, upload_to='invoice'),
        ),
    ]
