# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0004_auto_20170118_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
