# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0005_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation.'),
        ),
    ]
