# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0007_auto_20170123_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 23, 11, 15, 33, 90796, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
