# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0013_auto_20170124_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='no_of_licence',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of licence'),
        ),
    ]
