# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0014_auto_20170124_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='order_id',
            field=models.CharField(default='124274163376252', editable=False, max_length=20, unique=True, verbose_name='Order Id'),
        ),
    ]
