# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0020_auto_20170124_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_id',
            field=models.CharField(default='290126495396852', max_length=20, unique=True, verbose_name='Order Id'),
        ),
    ]
