# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0021_auto_20170124_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_request',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='orderinfo.OrderRequest', verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='order_id',
            field=models.CharField(default='441961692986115', max_length=20, unique=True, verbose_name='Order ID'),
        ),
    ]
