# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0022_auto_20170124_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_request',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=4564564465, max_length=20, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='order_id',
            field=models.CharField(default='574155919967382', max_length=20, unique=True, verbose_name='Order ID'),
        ),
    ]
