# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderinfo', '0025_auto_20170125_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Order ID'),
        ),
    ]
