# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamowner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='teamowner',
            name='organization_user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.DeleteModel(
            name='TeamOwner',
        ),
    ]
