# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170116_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
