# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_auto_20170116_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=256, verbose_name='Device Id')),
                ('device_name', models.CharField(blank=True, max_length=256, verbose_name='Device Name')),
                ('last_verified', models.DateTimeField(auto_now=True, verbose_name='Last verified')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamUser')),
            ],
        ),
    ]
